### Eudicots
#####################################################################################
[Nicotiana_benthamiana]
mRNA=/data/users/demartini/P-SAMS/p-sams_py/phytozome_inputs/Nbenthamianavar_NbeHZ1_946_v1.0.transcript.fa
sql=/data/users/demartini/P-SAMS/p-sams_py/db/Nicotiana_benthamiana_1.0.db


[Nicotiana_benthamiana_prueba]
mRNA=/data/users/demartini/P-SAMS/p-sams_py/phytozome_inputs/Nbenthamianavar_NbeHZ1_946_v1.0.transcript.fa
sql=/data/users/demartini/P-SAMS/p-sams_py/db/Nicotiana_benthamiana_prueba_2.0_prueba.db
